/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { MieterUeberschneidungAntwortDto } from '../models/mieter-ueberschneidung-antwort-dto';
import { mieterUeberschneidungControllerUeberschneidung } from '../fn/mieter-ueberschneidung/mieter-ueberschneidung-controller-ueberschneidung';
import { MieterUeberschneidungControllerUeberschneidung$Params } from '../fn/mieter-ueberschneidung/mieter-ueberschneidung-controller-ueberschneidung';

@Injectable({ providedIn: 'root' })
export class MieterUeberschneidungService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `mieterUeberschneidungControllerUeberschneidung()` */
  static readonly MieterUeberschneidungControllerUeberschneidungPath = '/validatoren/mieterueberschneidung';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `mieterUeberschneidungControllerUeberschneidung()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  mieterUeberschneidungControllerUeberschneidung$Response(params: MieterUeberschneidungControllerUeberschneidung$Params, context?: HttpContext): Observable<StrictHttpResponse<MieterUeberschneidungAntwortDto>> {
    return mieterUeberschneidungControllerUeberschneidung(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `mieterUeberschneidungControllerUeberschneidung$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  mieterUeberschneidungControllerUeberschneidung(params: MieterUeberschneidungControllerUeberschneidung$Params, context?: HttpContext): Observable<MieterUeberschneidungAntwortDto> {
    return this.mieterUeberschneidungControllerUeberschneidung$Response(params, context).pipe(
      map((r: StrictHttpResponse<MieterUeberschneidungAntwortDto>): MieterUeberschneidungAntwortDto => r.body)
    );
  }

}
