openapi: 3.0.0
paths:
  /validatoren/mieterueberschneidung:
    post:
      operationId: MieterUeberschneidungController_ueberschneidung
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MieterUeberschneidungAnfrageDTO'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MieterUeberschneidungAntwortDTO'
      tags:
        - MieterUeberschneidung
  /:
    get:
      operationId: AppController_getHello
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - App
  /beziehungen:
    get:
      operationId: BeziehungenController_beziehungen
      parameters:
        - name: kontaktId
          required: true
          in: query
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BeziehungAntwortDto'
      tags:
        - Beziehungen
    post:
      operationId: BeziehungenController_erstelleBeziehung
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BeziehungErstellenDto'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BeziehungAntwortDto'
      tags:
        - Beziehungen
  /beziehungen/{id}:
    get:
      operationId: BeziehungenController_beziehung
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BeziehungAntwortDto'
      tags:
        - Beziehungen
    patch:
      operationId: BeziehungenController_aendereBeziehung
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BeziehungAendernDto'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BeziehungAntwortDto'
      tags:
        - Beziehungen
    delete:
      operationId: BeziehungenController_loescheBeziehung
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BeziehungAntwortDto'
      tags:
        - Beziehungen
  /immobilien:
    get:
      operationId: ImmobilienController_immobilien
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ImmobilieAntwortMitBeziehungenDto'
      tags:
        - Immobilien
    post:
      operationId: ImmobilienController_erstelleImmobilie
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ImmobilieErstellenDto'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImmobilieAntwortMitBeziehungenDto'
      tags:
        - Immobilien
  /immobilien/{id}:
    get:
      operationId: ImmobilienController_immobilie
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImmobilieAntwortMitBeziehungenDto'
      tags:
        - Immobilien
    patch:
      operationId: ImmobilienController_aendereImmobilie
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ImmobilieAendernDto'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImmobilieAntwortMitBeziehungenDto'
      tags:
        - Immobilien
    delete:
      operationId: ImmobilienController_loescheImmobilie
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImmobilieAntwortMitBeziehungenDto'
      tags:
        - Immobilien
  /kontakte:
    get:
      operationId: KontakteController_kontakte
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/KontaktAntwortMitBeziehungenDto'
      tags:
        - Kontakte
    post:
      operationId: KontakteController_erstelleKontakte
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/KontaktErstellenDto'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KontaktAntwortMitBeziehungenDto'
      tags:
        - Kontakte
  /kontakte/{id}:
    get:
      operationId: KontakteController_kontakt
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KontaktAntwortMitBeziehungenDto'
      tags:
        - Kontakte
    patch:
      operationId: KontakteController_aendereKontakte
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/KontaktAendernDto'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KontaktAntwortMitBeziehungenDto'
      tags:
        - Kontakte
    delete:
      operationId: KontakteController_loescheKontakte
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KontaktAntwortMitBeziehungenDto'
      tags:
        - Kontakte
info:
  title: Scalara API
  description: Eine API für Scalara
  version: '1.0'
  contact: {}
tags:
  - name: scalara
    description: ''
servers: []
components:
  schemas:
    MieterUeberschneidungAnfrageDTO:
      type: object
      properties:
        id:
          type: string
        immobilienId:
          type: string
        startdatum:
          format: date-time
          type: string
        enddatum:
          format: date-time
          type: string
      required:
        - id
        - immobilienId
        - startdatum
        - enddatum
    MieterUeberschneidungAntwortDTO:
      type: object
      properties:
        ueberschneidung:
          type: boolean
      required:
        - ueberschneidung
    KontaktAntwortDto:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        strasse:
          type: string
        hausnummer:
          type: string
        postleitzahl:
          type: string
        stadt:
          type: string
        land:
          type: string
          enum:
            - Deutschland
            - Italien
            - Frankreich
      required:
        - id
        - name
        - strasse
        - hausnummer
        - postleitzahl
        - stadt
        - land
    ImmobilieAntwortDto:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        beschreibung:
          type: string
        strasse:
          type: string
        hausnummer:
          type: string
        postleitzahl:
          type: string
        stadt:
          type: string
        land:
          type: string
          enum:
            - Deutschland
            - Italien
            - Frankreich
      required:
        - id
        - name
        - beschreibung
        - strasse
        - hausnummer
        - postleitzahl
        - stadt
        - land
    BeziehungAntwortDto:
      type: object
      properties:
        id:
          type: string
        kontakt:
          $ref: '#/components/schemas/KontaktAntwortDto'
        immobilie:
          $ref: '#/components/schemas/ImmobilieAntwortDto'
        beziehungstyp:
          type: number
        dienstleistungstyp:
          type: number
        startdatum:
          type: string
          format: date-time
        enddatum:
          type: string
          format: date-time
      required:
        - id
        - kontakt
        - immobilie
        - beziehungstyp
        - startdatum
        - enddatum
    BeziehungErstellenDto:
      type: object
      properties:
        immobilienId:
          type: string
        kontaktId:
          type: string
        beziehungstyp:
          type: number
        dienstleistungstyp:
          type: number
        startdatum:
          format: date-time
          type: string
        enddatum:
          format: date-time
          type: string
      required:
        - immobilienId
        - kontaktId
        - beziehungstyp
        - dienstleistungstyp
        - startdatum
        - enddatum
    BeziehungAendernDto:
      type: object
      properties:
        immobilienId:
          type: string
        kontaktId:
          type: string
        beziehungstyp:
          type: number
        dienstleistungstyp:
          type: number
        startdatum:
          format: date-time
          type: string
        enddatum:
          format: date-time
          type: string
      required:
        - immobilienId
        - kontaktId
        - beziehungstyp
        - dienstleistungstyp
        - startdatum
        - enddatum
    BeziehungenEingefuegtDto:
      type: object
      properties:
        id:
          type: string
        immobilienId:
          type: string
        kontaktId:
          type: string
        beziehungstyp:
          type: number
        dienstleistungstyp:
          type: number
        startdatum:
          type: string
          format: date-time
        enddatum:
          type: string
          format: date-time
      required:
        - id
        - immobilienId
        - kontaktId
        - beziehungstyp
        - startdatum
        - enddatum
    ImmobilieAntwortMitBeziehungenDto:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        beschreibung:
          type: string
        strasse:
          type: string
        hausnummer:
          type: string
        postleitzahl:
          type: string
        stadt:
          type: string
        land:
          type: string
          enum:
            - Deutschland
            - Italien
            - Frankreich
        beziehungen:
          type: array
          items:
            $ref: '#/components/schemas/BeziehungenEingefuegtDto'
      required:
        - id
        - name
        - beschreibung
        - strasse
        - hausnummer
        - postleitzahl
        - stadt
        - land
        - beziehungen
    ImmobilieErstellenDto:
      type: object
      properties:
        name:
          type: string
        beschreibung:
          type: string
        strasse:
          type: string
        hausnummer:
          type: string
        postleitzahl:
          type: string
        stadt:
          type: string
        land:
          type: string
      required:
        - name
        - beschreibung
        - strasse
        - hausnummer
        - postleitzahl
        - stadt
        - land
    ImmobilieAendernDto:
      type: object
      properties:
        name:
          type: string
        beschreibung:
          type: string
        strasse:
          type: string
        hausnummer:
          type: string
        postleitzahl:
          type: string
        stadt:
          type: string
        land:
          type: string
      required:
        - name
        - beschreibung
        - strasse
        - hausnummer
        - postleitzahl
        - stadt
        - land
    KontaktAntwortMitBeziehungenDto:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        strasse:
          type: string
        hausnummer:
          type: string
        postleitzahl:
          type: string
        stadt:
          type: string
        land:
          type: string
          enum:
            - Deutschland
            - Italien
            - Frankreich
        beziehungen:
          type: array
          items:
            $ref: '#/components/schemas/BeziehungenEingefuegtDto'
      required:
        - id
        - name
        - strasse
        - hausnummer
        - postleitzahl
        - stadt
        - land
        - beziehungen
    KontaktErstellenDto:
      type: object
      properties:
        name:
          type: string
        strasse:
          type: string
        hausnummer:
          type: string
        postleitzahl:
          type: string
        stadt:
          type: string
        land:
          type: string
      required:
        - name
        - strasse
        - hausnummer
        - postleitzahl
        - stadt
        - land
    KontaktAendernDto:
      type: object
      properties:
        name:
          type: string
        strasse:
          type: string
        hausnummer:
          type: string
        postleitzahl:
          type: string
        stadt:
          type: string
        land:
          type: string
      required:
        - name
        - strasse
        - hausnummer
        - postleitzahl
        - stadt
        - land
