/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { KontaktAntwortMitBeziehungenDto } from '../../models/kontakt-antwort-mit-beziehungen-dto';
import { KontaktErstellenDto } from '../../models/kontakt-erstellen-dto';

export interface KontakteControllerErstelleKontakte$Params {
      body: KontaktErstellenDto
}

export function kontakteControllerErstelleKontakte(http: HttpClient, rootUrl: string, params: KontakteControllerErstelleKontakte$Params, context?: HttpContext): Observable<StrictHttpResponse<KontaktAntwortMitBeziehungenDto>> {
  const rb = new RequestBuilder(rootUrl, kontakteControllerErstelleKontakte.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<KontaktAntwortMitBeziehungenDto>;
    })
  );
}

kontakteControllerErstelleKontakte.PATH = '/kontakte';
