/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { KontaktAntwortMitBeziehungenDto } from '../../models/kontakt-antwort-mit-beziehungen-dto';

export interface KontakteControllerKontakte$Params {
}

export function kontakteControllerKontakte(http: HttpClient, rootUrl: string, params?: KontakteControllerKontakte$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<KontaktAntwortMitBeziehungenDto>>> {
  const rb = new RequestBuilder(rootUrl, kontakteControllerKontakte.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<KontaktAntwortMitBeziehungenDto>>;
    })
  );
}

kontakteControllerKontakte.PATH = '/kontakte';
