/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BeziehungAntwortDto } from '../../models/beziehung-antwort-dto';

export interface BeziehungenControllerLoescheBeziehung$Params {
  id: string;
}

export function beziehungenControllerLoescheBeziehung(http: HttpClient, rootUrl: string, params: BeziehungenControllerLoescheBeziehung$Params, context?: HttpContext): Observable<StrictHttpResponse<BeziehungAntwortDto>> {
  const rb = new RequestBuilder(rootUrl, beziehungenControllerLoescheBeziehung.PATH, 'delete');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BeziehungAntwortDto>;
    })
  );
}

beziehungenControllerLoescheBeziehung.PATH = '/beziehungen/{id}';
