/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BeziehungAntwortDto } from '../../models/beziehung-antwort-dto';
import { BeziehungErstellenDto } from '../../models/beziehung-erstellen-dto';

export interface BeziehungenControllerErstelleBeziehung$Params {
      body: BeziehungErstellenDto
}

export function beziehungenControllerErstelleBeziehung(http: HttpClient, rootUrl: string, params: BeziehungenControllerErstelleBeziehung$Params, context?: HttpContext): Observable<StrictHttpResponse<BeziehungAntwortDto>> {
  const rb = new RequestBuilder(rootUrl, beziehungenControllerErstelleBeziehung.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BeziehungAntwortDto>;
    })
  );
}

beziehungenControllerErstelleBeziehung.PATH = '/beziehungen';
