/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ImmobilieAntwortMitBeziehungenDto } from '../../models/immobilie-antwort-mit-beziehungen-dto';
import { ImmobilieErstellenDto } from '../../models/immobilie-erstellen-dto';

export interface ImmobilienControllerErstelleImmobilie$Params {
      body: ImmobilieErstellenDto
}

export function immobilienControllerErstelleImmobilie(http: HttpClient, rootUrl: string, params: ImmobilienControllerErstelleImmobilie$Params, context?: HttpContext): Observable<StrictHttpResponse<ImmobilieAntwortMitBeziehungenDto>> {
  const rb = new RequestBuilder(rootUrl, immobilienControllerErstelleImmobilie.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ImmobilieAntwortMitBeziehungenDto>;
    })
  );
}

immobilienControllerErstelleImmobilie.PATH = '/immobilien';
