/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ImmobilieAntwortMitBeziehungenDto } from '../../models/immobilie-antwort-mit-beziehungen-dto';

export interface ImmobilienControllerImmobilie$Params {
  id: string;
}

export function immobilienControllerImmobilie(http: HttpClient, rootUrl: string, params: ImmobilienControllerImmobilie$Params, context?: HttpContext): Observable<StrictHttpResponse<ImmobilieAntwortMitBeziehungenDto>> {
  const rb = new RequestBuilder(rootUrl, immobilienControllerImmobilie.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ImmobilieAntwortMitBeziehungenDto>;
    })
  );
}

immobilienControllerImmobilie.PATH = '/immobilien/{id}';
