/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { BeziehungAendernDto } from './models/beziehung-aendern-dto';
export type { BeziehungErstellenDto } from './models/beziehung-erstellen-dto';
export type { ImmobilieAendernDto } from './models/immobilie-aendern-dto';
export type { ImmobilieErstellenDto } from './models/immobilie-erstellen-dto';
export type { KontaktAendernDto } from './models/kontakt-aendern-dto';
export type { KontaktErstellenDto } from './models/kontakt-erstellen-dto';
