/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { BeziehungAendernDto } from './models/beziehung-aendern-dto';
export type { BeziehungAntwortDto } from './models/beziehung-antwort-dto';
export type { BeziehungenEingefuegtDto } from './models/beziehungen-eingefuegt-dto';
export type { BeziehungErstellenDto } from './models/beziehung-erstellen-dto';
export type { ImmobilieAendernDto } from './models/immobilie-aendern-dto';
export type { ImmobilieAntwortDto } from './models/immobilie-antwort-dto';
export type { ImmobilieAntwortMitBeziehungenDto } from './models/immobilie-antwort-mit-beziehungen-dto';
export type { ImmobilieErstellenDto } from './models/immobilie-erstellen-dto';
export type { KontaktAendernDto } from './models/kontakt-aendern-dto';
export type { KontaktAntwortDto } from './models/kontakt-antwort-dto';
export type { KontaktAntwortMitBeziehungenDto } from './models/kontakt-antwort-mit-beziehungen-dto';
export type { KontaktErstellenDto } from './models/kontakt-erstellen-dto';
