/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MieterUeberschneidungAnfrageDto } from '../../models/mieter-ueberschneidung-anfrage-dto';
import { MieterUeberschneidungAntwortDto } from '../../models/mieter-ueberschneidung-antwort-dto';

export interface MieterUeberschneidungControllerUeberschneidung$Params {
      body: MieterUeberschneidungAnfrageDto
}

export function mieterUeberschneidungControllerUeberschneidung(http: HttpClient, rootUrl: string, params: MieterUeberschneidungControllerUeberschneidung$Params, context?: HttpContext): Observable<StrictHttpResponse<MieterUeberschneidungAntwortDto>> {
  const rb = new RequestBuilder(rootUrl, mieterUeberschneidungControllerUeberschneidung.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MieterUeberschneidungAntwortDto>;
    })
  );
}

mieterUeberschneidungControllerUeberschneidung.PATH = '/validatoren/mieterueberschneidung';
