/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BeziehungErstellenDto {
  beziehungstyp: number;
  dienstleistungstyp: number;
  enddatum: string;
  immobilienId: string;
  kontaktId: string;
  startdatum: string;
}
