/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BeziehungenEingefuegtDto {
  beziehungstyp: number;
  dienstleistungstyp?: number;
  enddatum: string;
  id: string;
  immobilienId: string;
  kontaktId: string;
  startdatum: string;
}
