/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ImmobilieAendernDto {
  beschreibung: string;
  hausnummer: string;
  land: string;
  name: string;
  postleitzahl: string;
  stadt: string;
  strasse: string;
}
