/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MieterUeberschneidungAnfrageDto {
  enddatum: string;
  id: string;
  immobilienId: string;
  startdatum: string;
}
